apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: colorgateway
  namespace: default
spec:
  meshName: appmesh-lab
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: "colorgateway.default.svc.cluster.local"
  backends:
    - virtualService:
        virtualServiceName: "colorteller.default.svc.cluster.local"
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: colorteller
  namespace: default
spec:
  meshName: appmesh-lab
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: "colorteller.default.svc.cluster.local"
---
#black 
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: colorteller-black
  namespace: default
spec:
  meshName: appmesh-lab
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: "colorteller-black.default.svc.cluster.local"
---
#blue
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: colorteller-blue
  namespace: default
spec:
  meshName: appmesh-lab
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: "colorteller-blue.default.svc.cluster.local"
---
#red
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: colorteller-red
  namespace: default
spec:
  meshName: appmesh-lab
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: "colorteller-red.default.svc.cluster.local"